### ISSUE TITLE
'System.NullReferenceException' occurred in BitMiracle.LibTiff.NET.dll

### ISSUE THREAD

**Issue by janoschsimon** [BitMiracle/libtiff.net#10]
hey there im write a program for a conversion of an generic .raw to .dng and it works fine exept those two tifftags:

private const long white = 3576, black = 512;
.
.
 tif.SetField(TiffTag.WHITELEVEL, 1, white);
 tif.SetField(TiffTag.BLACKLEVEL, 1, black);
.

when i debug this exeption is thrown:
A first chance exception of type 'System.NullReferenceException' occurred in BitMiracle.LibTiff.NET.dll
Additional information: Object reference not set to an instance of an object.
If there is a handler for this exception, the program may be safely continued.
i used the precompiled dll and compiled it on my own im using vs studio 2013 express desktop

call stacks:
in tiff.cs line 2885 return m_tagmethods.SetField(this, tag, FieldValue.FromParams(value));
and then the final break in
TiffTagMethods.cs lin 499  Buffer.BlockCopy(apBytes, 0, td.td_customValues[tvIndex].value, 0, Math.Min(apBytes.Length, td.td_customValues[tvIndex].value.Length));

hope anybody can help cause when i need white and black level :-) when i remove the two the conversion works fine.

thx janosch

**Comment by Bobrovsky** [comment]
Janosch,

I suspect you are getting this issue because tags expects an array not a single integer. 
http://www.awaresystems.be/imaging/tiff/tifftags/whitelevel.html

**Comment by janoschsimon** [comment]
wow that was fast replay thx :-) but the the values i have are only one value? im trying to port this code from c on the osx side to c# on the windows side and your dll was the missing link caus i failed to compile the orginal libtiff library under windows :-) 
one strange thing i observed under c in osx was that there was white and blacklevel reference: 
	TIFFSetField (tif, TIFFTAG_WHITELEVEL, 1, &white);
	TIFFSetField (tif, TIFFTAG_BLACKLEVEL, 1, &black);
i tired this under c# but it didnt work

would you mind telling me how you whould implement my white and black level as an array? 

thx janosch

**Comment by Bobrovsky** [comment]
Please try this

tif.SetField(TiffTag.WHITELEVEL, 1, new long[] { white });
tif.SetField(TiffTag.BLACKLEVEL, 1, new long[] { black });

**Comment by janoschsimon** [comment]
sadly the same :-/

**Comment by Bobrovsky** [comment]
Ok, so you probably found a bug in the library. You are welcome to try and fix it then send us a pull request :-)

**Comment by janoschsimon** [comment]
oh gosh im just a beginner and happy to find the possition but no clue how to fix it :-( any other thing i can try? :-)

**Comment by Milster** [comment]
As mentioned via E-Mail:

Your constants should be of type int, which will solve the NULLReference. (GetBytes() doesn't like INT64 values)
Whitelevel has the bool passCount set to false. As far as I can see the lines should be:

tif.SetField(TiffTag.WHITELEVEL, white);
tif.SetField(TiffTag.BLACKLEVEL, 1, black);

If you change those few things, everything should be fine.

The only bug, if you want to call it that, is the fact, that the GetBytes method can't handle INT64 values.

**Comment by Bobrovsky** [comment]
@Milster Thank you.

**Comment by janoschsimon** [comment]
@Milster Peter thx again 10000000 times he solved the problem quick and dirty but it works YAY :dancers:

**Comment by Milster** [comment]
At some point someone should take a look at TiffTag.WHITELEVEL and TiffTag.BLACKLEVEL .

I think WHITELEVEL should indeed has it's passcount set to true. And at least in this case, the fieldinfo of blacklevel always responded with a rational value, even if the inserted value was an int.

This 'nullReference'-issue though can be marked as solved.

**Comment by mudcamper** [comment]
This still doesn't work for me. Milster's suggestion works for BLACKLEVEL, but if I set WHITELEVEL, it either gets a null reference exception when I set it, or it crashes later with an overflow exception when I WriteDirectory (depending on the syntax that I use)
