### ISSUE TITLE
"the parameter is incorrect" windows api error

### ISSUE THREAD

**Issue by xela-trawets** [BitMiracle/libtiff.net#100]
Hitting this on files where all the IFDs (except the first) are at the end of the file, and the file is > 2^31 bytes.
ImageJ reads the files just fine.

I can traverse the IFDs myself, and call 
tiff.SetSubDirectory(ifdOffset);

While that workaround seems to work fine for me, this probably bites others too.

Now this is a bit of an edge case, but are you interested in a pr for it 
(I think that's the Jargon)

A

**Comment by xela-trawets** [comment]
Found it, 
Will submit.

**Comment by Bobrovsky** [comment]
Thank you for the fix.
