### ISSUE TITLE
Update the license file, so it integrates with GitHub nicely

### ISSUE THREAD

**Issue by Mertsch** [BitMiracle/libtiff.net#102]
Currently this link does not work. 
![lic](https://github.com/BitMiracle/libtiff.net/assets/9402861/c7435aee-414f-48e3-9cb7-b57b10a53a5e)

# Solution
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
> In the file name field, type LICENSE or LICENSE.md (with all caps).

**Comment by shibaev** [comment]
Could you please clarify what you mean by "this link does not work"? For me, the "View license" link properly shows the content of https://github.com/BitMiracle/libtiff.net/blob/master/license.txt (checked with Chrome, Firefox, Edge)

**Comment by Mertsch** [comment]
Hmmm that is strange, my Fx won't let me click the link, in Edge it works ... I guess my Fx is broken somehow 😕
It also does not work here https://github.com/nietras/Sep#MIT-1-ov-file

Closing this issue.
