### ISSUE TITLE
ComputeTile returns invalid number of tile 

### ISSUE THREAD

**Issue by j-hudecek** [BitMiracle/libtiff.net#105]
I have a tiff with a directory with 

td_imagelength 2560
td_imagewidth 3132
td_imagedepth 1
td_tiledepth 1
td_tilelength 512
td_tilewidth 512

Calling 

_image.ComputeTile(0, 2560, 0, 0)

returns 35, But calling ReadEncodedTile with that prints out 

    35: Tile out of range, max 35

reads no data and returns -1. ComputeTile docs say "A valid tile number is always returned" so it looks like a bug - in my code and yours ;)

**Comment by shibaev** [comment]
The `tile` argument in `ReadEncodedTile` is zero-based. In your example, the valid values lie in [0; 34] range.
