### ISSUE TITLE
Visual Studio 2015 Compilation Failure

### ISSUE THREAD

**Issue by trailway** [BitMiracle/libtiff.net#12]
Compilation of LibTiff\LibJpeg\Internal\phuff_entropy_decoder.cs fails using Visual Studio 2015.

LibTiff\LibJpeg\Internal\phuff_entropy_decoder.cs(458,21,458,68): error CS0675: Bitwise-or operator used on a sign-extended operand; consider casting to a smaller unsigned type first

I can suppress the error but am not familiar with the code so I don't know whether or not this is a real issue.

**Comment by devedse** [comment]
Also encountered this one yesterday after installing Visual Studio 2015

**Comment by Bobrovsky** [comment]
@trailway @devedse Thank you. The issue is fixed in the latest commit.
