### ISSUE TITLE
Error opening 4 bitpersample TIFF in LZW compression

### ISSUE THREAD

**Issue by stumpdk** [BitMiracle/libtiff.net#16]
When I'm trying to open a TIF image with LZW compression having a bit depth of 4 bitspersample, I get the error "Sorry, can not handle image".

I can see that the method pickContigCase(), when handling bitmaps based on LZW-compression and RGB photometric, only take into account situations in which the bitspersample value is either 8 or 16 
[(it happens here)](https://github.com/BitMiracle/libtiff.net/blob/master/LibTiff/TiffRgbaImage.cs#L1330).

What if the bitspersample is 4?

**Comment by Bobrovsky** [comment]
Bo,
The library handles many TIFF flavors but not all of them. You have a case no one used before. Or at least no one bothered to write code for. 

You are more than welcome to write the missing code yourselves and post a pull request.
