### ISSUE TITLE
StrongName sign the assemblies

### ISSUE THREAD

**Issue by patrickmaurer** [BitMiracle/libtiff.net#2]
Added libtiff.net using NuGet to my solution today. Unfortunately I could not use it directly, because the assembly was not StrongName signed.

Please enable solutions that are itself StrongName signed to use libtiff.net directly by sign your assembl(y|ies).

Btw: thanks for your work porting this library to managed C#!

**Comment by Bobrovsky** [comment]
Unfortunately, signed assembly will not work for those who do not sign their code. Maintaining two versions of NuGet package is not very convenient too.

At the same time there are at least three options for those who need signed assemblies:
1. Sign assemblies using some pre-processing tools. 
https://www.nuget.org/packages/Nivot.StrongNaming/
http://blog.maartenballiauw.be/post/2014/09/10/Automatically-strong-name-signing-NuGet-packages.aspx

2. Use source code to produce your own signed assembly.

3. Include source code of LibTiff.Net in your source code.

**Comment by patrickmaurer** [comment]
Thank you for your reply.

I don't know where you have the information from, that an unsigned assembly cannot use/reference a strong-named assembly. This is wrong, it't no problem at all to do this.
For example, you can start a new C# project in Visual Studio and add a reference to log4net using nuget. You'll end up having a unsigned project using a strong-named log4net assembly.

Could you reconsider your opinion?

**Comment by Bobrovsky** [comment]
Thank you for the information. I was wrong. Signed assemblies _can_ be used in unsigned applications.

Starting from 2.4.509 we sign assemblies we push on NuGet. 

The new (signed) version is available there
https://www.nuget.org/packages/BitMiracle.LibTiff.NET/

**Comment by patrickmaurer** [comment]
Thank you, this is awesome! Verified, it works as expected.
