### ISSUE TITLE
how write tiffs with OJPEG compression type

### ISSUE THREAD

**Issue by mikiones** [BitMiracle/libtiff.net#21]
Its deprecated. yes but old applications and hardware required it to be in this format. its there any way to make it work with net.LibTIff?

**Comment by Bobrovsky** [comment]
No, there is no way to create a TIFF with OJPEG compression using LibTiff.Net. And we are not planning to add such a way.

The main reason: almost every application producing or consuming TIFF images with OJPEG compression has it's own quirks and bugs and misinterpretations of the standard. So there is no point in making general-purpose library produce non-standard images for a number of non-standards compliant consumer.
