### ISSUE TITLE
32 Bits per Sample support

### ISSUE THREAD

**Issue by brianbourke75** [BitMiracle/libtiff.net#22]
Hello,  I am working on a project which requires 32 bits per sample support.  Is it possible to implement this?  I am perfectly willing to put my own time towards this but I wanted to get a sense of the difficulty.

**Comment by Bobrovsky** [comment]
Hello Brian,

I think it's possible. Amount of time required to add such support really depends on features you need (reading, reading/writing, RGBA conversion, etc.). 

I anticipate the task to be tedious but probably not very hard.

**Comment by brianbourke75** [comment]
Right now I _think_ I only need to read 32 bit grayscale images, but definitely no write support will be required.  Any advice on where to start?

**Comment by Bobrovsky** [comment]
I would start from finding out what compression scheme is used to encode image. I will probably be Deflate or Zip. Image can even be uncompressed. 

Then I would make sure all corresponding codecs in the library can decode 32bit grayscale images.

When you have a codec which can decode image data you can read image data as decoded bytes (Tiff.ReadEncodedStrip). But you will have to process those bytes yourselves (e.g. pack each 4 bytes into one 32 bit sample).

**Comment by carlosngis** [comment]
Hi Sergey

We are working with 32 bitspersample TIF images and wondering if there are any plans to add support for it 
We'd like to be able to extract the RGBA image and convert it into a .NET System.Drawing.Image (see attachment)
[32bps.zip](https://github.com/BitMiracle/libtiff.net/files/1036966/32bps.zip)

Thanks
