### ISSUE TITLE
Exception when reading deep tiff stacks

### ISSUE THREAD

**Issue by jeremy7nelson** [BitMiracle/libtiff.net#23]
Open a tiff stack with thousands of pages. Read page 3500 (in my testing it started failing on page 3495 but this may vary). System.IO.Exception thrown in ReadScanline. I tracked the problem down to Tiff_DirRead.cs:783 in fetchLong8Array. dir.tdir_offset is cast to (int) and should be (long).

**Comment by Bobrovsky** [comment]
Thank you.

How large is your TIFF in bytes?

**Comment by jeremy7nelson** [comment]
I tested with several files and it didn't really matter as long as there were enough pages. 2.5GB, 6GB, 8GB. I believe they were all saved as big tiff though.

**Comment by jeremy7nelson** [comment]
Attaching a patch to fix this bug.

[fix.zip](https://github.com/BitMiracle/libtiff.net/files/400048/fix.zip)

**Comment by shibaev** [comment]
Thank you, @jeremy7nelson
