### ISSUE TITLE
SwabShort and Tags > 0x7FFF

### ISSUE THREAD

**Issue by eugenefedoto** [BitMiracle/libtiff.net#24]
I'm working on my own code. I was examining how you swap bytes using your Swab functions, particularly the SwabShort. 

https://github.com/BitMiracle/libtiff.net/blob/master/LibTiff/Tiff.cs#L5681

There's one issue I'm not sure your code takes into account (I haven't thoroughly looked). Your SwabShort accepts signed values, limiting it to max positive of 0x7FFF. What happens when you try to get a tag value of 0x8769 (Exif IFD)? That won't fit, so the value ends up overflowing, and you get a non-existent tag name.

If you have taken care of this issue, let me know how. Otherwise, all I did was change the shorts to ushorts.

**Comment by hangy** [comment]
Shouldn't this fit well in `SwabLong(ref int value)`?

**Comment by eugenefedoto** [comment]
I guess it should. But I'm getting an error that says "cannot convert from ref short to ref int". My research brought me to this [link](https://blogs.msdn.microsoft.com/ericlippert/2009/03/19/representation-and-identity/), which is also included in LibTiff's documentation. Unfortunately, I don't have much time to figure everything out, and probably will use ushort for my code.

```
byte[] bArray = reader.ReadBytes(2); // get the Tag bytes

short tag = BitConverter.ToInt16(bArray, 0); // convert the byte array to a short

ImageFileHeader.SwabLong(ref tag);  // not allowing me to use tag here
                                   // because it's a short, and I can't cast it into an int
```

**Comment by Bobrovsky** [comment]
@eugenefedoto Thank you for the observation.
@hangy Thank you for looking into this.

It might be a good idea to have `SwabUShort(ref ushort value)` or something like this but we never needed it. 

And we wanted LibTiff.Net to be [CLS compliant](https://msdn.microsoft.com/en-us/library/12a7a7h3(v=vs.110).aspx) and this means we must not have methods with unsigned types in API.
