### ISSUE TITLE
Load data from byte array rather than from file

### ISSUE THREAD

**Issue by guillaume--** [BitMiracle/libtiff.net#25]
Is it possible to load data from byte array (instead of file)? I am happy to contribute.

**Comment by shibaev** [comment]
Yes, it is possible. Tiff.ClientOpen method accepts "clientData" parameter which should actually be a System.IO.Stream. Wrap your byte array to a stream (e.g. MemoryStream) and pass to ClientOpen.

It would be helpful to change type from "object" to "Stream" for Tiff.m_clientdata and for all "object clientData" method parameters. Anyway non-stream client datas are not supported - TiffStream class strictly casts type to Stream.

**Comment by guillaume--** [comment]
Awesome thanks.
