### ISSUE TITLE
Cannot load image that contains 64-bit exif tags

### ISSUE THREAD

**Issue by volgunin** [BitMiracle/libtiff.net#27]
There are two problems that cause the issue:

1. Method 'public byte[] GetBytes()' in FieldValue.cs ignores long[] and ulong[] data types and returns null.

2. Constants typemask, bigTypeshift, and litTypeshift in Tiff_Open.cs are typed incorrectly. TiffType enum has a value gap between IFD and LONG8 (13 and 16) that is not reflected in constants' values. As a result method extractData writes outside of array boundaries.

**Comment by Bobrovsky** [comment]
Thanks for the bug report. We would be happy if you send us a patch or pull request for the fix.

**Comment by volgunin** [comment]
Done. Pull request is there.

**Comment by Bobrovsky** [comment]
Thank you!
