### ISSUE TITLE
Build fails because "AssemblyVersion.cs" is missing

### ISSUE THREAD

**Issue by shoelzer** [BitMiracle/libtiff.net#3]
I made a clone from Github, opened `LibTiff.NET_NoSilverlight.sln`, and tried to build the LibTiff project. The build fails because "AssemblyVersion.cs" is missing. Please add it to the repo so I can build after a fresh clone.

**Comment by Bobrovsky** [comment]
It's strange.

There is a pre-build step that _generates_ the AssemblyVersion.cs. I've checked the scenario you described and everything worked as expected.

Since the file doesn't get generated, you might want to find why the pre-build step is not executed or why it fails.

**Comment by shoelzer** [comment]
I see. The pre-build step doesn't work for me because git is not on my Visual Studio command line path. Is that something you do manually, or does it happen as side effect of using/installing some tool?

**Comment by Bobrovsky** [comment]
I use GitHub for Windows (https://windows.github.com/). It installs command line tools too.
