### ISSUE TITLE
Is the default build thread safe?

### ISSUE THREAD

**Issue by coderb** [BitMiracle/libtiff.net#30]
I see some code that is conditional upon THREAD_SAFE_LIBTIFF being set.

It appears that the library is not threadsafe unless this token is set, however the default project does not seem to set it.

If I am seeing things correctly, it seems like a better default would be that the library should be thread safe.

**Comment by Bobrovsky** [comment]
Yes, the default project does not define THREAD_SAFE_LIBTIFF and thus is not thread safe. All instances of Tiff class use the same error / warning handler. 

Original libtiff library is not thread safe, too. And we wanted API and behavior of original library and our version to be as close as possible.

If you like us need a thread safe version then just define THREAD_SAFE_LIBTIFF and adapt your code accordingly.
