### ISSUE TITLE
TiffTag.XMLPACKET being parsed as Int, not Byte[ ]

### ISSUE THREAD

**Issue by EFinley** [BitMiracle/libtiff.net#31]
The title pretty much says it all.

I'm constructing an XML packet using XmpCore, which comes out as a string in C# terms.  An attempt to call `myTiff.SetField(TiffTag.XMLPACKET, xmpPacket)` throws an error with a stack trace which shows that it is trying to feed my input into `Int.TryParse( )` for reasons I cannot figure out, despite looking though the source code for `SetField( )`.  It certainly appears to be the case that the parser inside `SetField` thinks the type of TiffTag.XMLPACKET is Int rather than Byte; can't tell from the stack trace whether it thinks it's a single Int or a stack of N of them.

I looked into casting the string to a `FieldValue` or `FieldValue[ ]`, so as to be able to use the `GetBytes( )` method, but without success.

This is not critical to me; I've worked around this by implementing a custom tag (as described in the samples) of type Byte, and I think it's working fine.  _(An aside, there... in your samples on custom tags, you use `-1` instead of `TiffFieldInfo.Variable`, which seems like very poor practice, especially in an example.  And the documentation on `TiffFieldInfo.Variable2` leaves me mystified on what I would want it for and might benefit from a rewrite.)_

But the issue with XMLPACKET still seemed worth bringing to your attention.
Cheers!

**Comment by Bobrovsky** [comment]
Thank you for the report.

According to http://www.awaresystems.be/imaging/tiff/tifftags/xmp.html, the `TiffTag.XMLPACKET` field's value should be specified as N bytes, not string. 

As for the samples, yes, some of them can be improved/corrected. Please feel free to send us a pull request with corrections.

**Comment by EFinley** [comment]
Yeah, I was just noticing that.

I assume, then, that I can't (directly) make use of the built-in Latin1 encoding inside FieldValue, since I need to supply both the byte array and its length.  I'll have to do my own encoding with regards to that, or just use my own string- or byte[ ]- valued custom type.  Yes?

**Comment by Bobrovsky** [comment]
I believe yes, you  should convert you string to byte[] or use a custom field.

**Comment by EFinley** [comment]
Got it.  Pull request tossed your way.  Thanks for the fast response!
