### ISSUE TITLE
How to set field Orientation in tiff 

### ISSUE THREAD

**Issue by rmorejon** [BitMiracle/libtiff.net#33]
var stream = new MemoryStream(File.ReadAllBytes(@"D:\1.tif"));
            using (Tiff input = Tiff.ClientOpen("in-memory", "a", stream, new TiffStream()))
            {
                input.SetDirectory(0);
                var result=input.SetField(TiffTag.ORIENTATION, BitMiracle.LibTiff.Classic.Orientation.RIGHTBOT);
                input.CheckpointDirectory();
                input.Close();
}

no working !!!

result is true but no change the orientation in the tiff

**Comment by rmorejon** [comment]
using (Tiff input = Tiff.Open(@"D:\1.tif", "a"))
            {
                input.SetDirectory(0);
               input.SetField(TiffTag.ORIENTATION, BitMiracle.LibTiff.Classic.Orientation.BOTLEFT);
                input.RewriteDirectory();
             }
Work!!!

but I need use
 using (Tiff input = Tiff.ClientOpen("in-memory", "a", stream, new TiffStream()))

it does not work

**Comment by Bobrovsky** [comment]
Please clarify what does "no working !!!" means.

**Comment by rmorejon** [comment]
var stream = new MemoryStream(File.ReadAllBytes(@"D:\1.tif"));
using (Tiff input = Tiff.ClientOpen("in-memory", "a", stream, new TiffStream()))
{
 input.SetDirectory(0);
 var result=input.SetField(TiffTag.ORIENTATION, BitMiracle.LibTiff.Classic.Orientation.RIGHTBOT);
  input.RewriteDirectory();
}

In this case the field ORIENTATION no save correctly
Open the tiff with irfanView, the image no show rotated 

But use 

 using (Tiff input = Tiff.Open(@"D:\1.tif", "a"))
        {
            input.SetDirectory(0);
           input.SetField(TiffTag.ORIENTATION, BitMiracle.LibTiff.Classic.Orientation.BOTLEFT);
            input.RewriteDirectory();
         }
works correctly !!!

I need to use the variant Tiff input = Tiff.ClientOpen("in-memory", "a", stream, new TiffStream())
because I have the memory tiff

**Comment by Bobrovsky** [comment]
Please note that you use different values for TiffTag.ORIENTATION in the first and the second cases.

Please also note that the first code block affects memory stream only and you should save the memory stream into a file.

**Comment by Bobrovsky** [comment]
Please also note that you create non-expandable memory stream.

**Comment by rmorejon** [comment]
what I want is to change the orientation field of a tiff because rotate the image. I have the tiff loaded into memory, then when I finish the album except pa verify

**Comment by rmorejon** [comment]
Help me ?

**Comment by jaydeep6720** [comment]
`using (Tiff input = Tiff.Open(@"D:\\TRIAL DESIGNS\\ROTARY\\01.tif", "a"))
            {
               
                input.SetDirectory(0);
                int width = input.GetField(TiffTag.IMAGEWIDTH)[0].ToInt();
                int height = input.GetField(TiffTag.IMAGELENGTH)[0].ToInt();

                input.SetField(TiffTag.ORIENTATION, BitMiracle.LibTiff.Classic.Orientation.BOTLEFT);
                input.SetField(TiffTag.EXIF_PIXELXDIMENSION,height);
                input.SetField(TiffTag.EXIF_PIXELYDIMENSION,width);
                input.RewriteDirectory();
                input.Close();
            }`

> I am Using this Code to rotate Image. Operation Successful & also visible in Irfan View. But when I load it in CYOTEK picture box Or Default picture box it doesn't reflects the rotation of Image.

**Comment by makingbloke** [comment]
This doesn’t actually rotate the bitmap it just sets a flag suggesting how
it should be rotated. Not all Tiff readers will use the tag or honour the
value (I seem to recall it’s not a mandatory tag).

Cheers
