### ISSUE TITLE
Use of Offset in GetRaster() to get a portion of image?

### ISSUE THREAD

**Issue by TomQv** [BitMiracle/libtiff.net#35]
How is the offset-parameter used in TiffRgbaImage.GetRaster()?
I'm trying to read a small rectangle portion from a big tiff-image with GetRaster, but all I get is IndexOutOfRange-exception.
For example:
- image is 10000x10000 pixel
- I need a rectangle of 200x200 pixel starting at left/top 100,100

```
var rect= new Rectangle(100, 100, 200, 200);
var raster = new int[rect.Width * rect.Height];
var offset = image.Width  * rect.Top + rect.Left;
 _tiffRgba.GetRaster(raster, offset, rect.Width, rect.Height);
```

Thanks for help.
Tom

**Comment by Bobrovsky** [comment]
Offset parameter has the following description:

`<param name="offset">The zero-based byte offset in <paramref name="raster"/> at which to begin storing decoded bytes.</param>`

**Comment by TomQv** [comment]
I know the description, I just don't understand how to use it in my case.
Thats why I'm asking for help.
Thanks alot...

**Comment by devedse** [comment]
Since it describes "at which to begin storing decoded bytes" I assume it refers to the index of the array you want to store the data in. So basically, offset should be 0 since you want to store it at the start of your int array.

**Comment by TomQv** [comment]
ok, but I don't want the whole image, just a recangle portion.
So this is not possible with GetRaster()?
Or maybe with another high-level function?

**Comment by devedse** [comment]
It is. Just remove the line where you calculate the offset and pass 0 instead.

**Comment by TomQv** [comment]
Then a portion starting from image-origin is returned.
Or is there another way to pass the left/top-corner of the portion I want to read?

**Comment by devedse** [comment]
The offset should be the offset within the array you store data at, it shouldn't have anything to do with the position in the image. That's what you already define using the rectangle.
