### ISSUE TITLE
Add build for TargetFrameworkVersion 4.0 or 4.5

### ISSUE THREAD

**Issue by gpetrou** [BitMiracle/libtiff.net#36]
Currently, there is a 2.0 TargetFrameworkVersion build.
Would it be possible to add another one for 4.0 or 4.5?
If that fits your plans I could add a PR.

**Comment by gpetrou** [comment]
OK. I will prepare a PR. I will add another project for .NET 4.0
I see there are two solutions (LibTiff.NET.2012.sln and LibTiff.NET.sln)
Is the first one obsolete and should be removed?
I was planning to only edit the LibTiff.NET.sln
Also, I cannot find a nuspec file to include the new dll.
Is this something you keep separate?
And is there a public CI you use so that I can check my PR?

**Comment by Bobrovsky** [comment]
I removed LibTiff.NET.2012.sln from the repo. So you don't need to do anything about it.
We keep nuspec separate, well update it ourselves later.
Please make project for .NET4 the default one. 
We use unit tests project to check if there are any regressions. You can run them locally using NUnit test runner.

**Comment by Bobrovsky** [comment]
Thank you for PRs, I will publish new NuGet shortly.
