### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by brianarmendariz** [BitMiracle/libtiff.net#39]
Wanted to let you know that the builds after 2.4.571 are causing unresolved references. It may be a versioning issue for I have .NET 4.6. Thanks.

**Comment by Bobrovsky** [comment]
Hello,

Thank you for the bug report. Can you please provide more information about the issue? What version/flavor of the library you are using? What references are unresolved?

**Comment by Bobrovsky** [comment]
I am closing the issue since you have not responded.
