### ISSUE TITLE
"SOFTWARE" tag corrupt tiff image when there's '.' char it embedded value

### ISSUE THREAD

**Issue by roth-ddd** [BitMiracle/libtiff.net#41]
Dear Team,

Thanks for creating this library in the first place, it a really great one. When using version 2.3.xx, everything work fine, however once we update the new lib, we notice one bug. 

We use Tiff class SetField() to set tag to the tiff image, the tag with we test with is "SOFTWARE" tag that causing the problem, the value that we put in is "V3.1". we then CheckpointDirectory() to save the new file => tiff image become black (corrupted). However if we set the value into "V31", everything is working find. Do you happen to experience something like this before? Why is that '.' char is causing the problem?

Here is our sample code
`private static Tiff.TiffExtendProc m_parentExtender;
 public static void embedTags(string fileName, List<TiffTagField> tags)
        {
            m_parentExtender = Tiff.SetTagExtender(TagExtender);

            string existingTiffName = string.Format("{0}~.tif", fileName);
            File.Copy(fileName, existingTiffName, true);

            using (Tiff image = Tiff.Open(existingTiffName, "a"))
            {
                image.SetDirectory(0);
                foreach (var t in tags)
                {
                    TiffTag tag = (TiffTag)t.Id;
                    image.SetField(tag, t.Value);
                }
                image.CheckpointDirectory(); //after this line new tiff image is create+tag is embedded, and it now become black.
            }
}`

**Comment by roth-ddd** [comment]
found the solution here.
http://stackoverflow.com/questions/11916277/issue-when-trying-to-update-tags-on-a-tiff-image

**Comment by Bobrovsky** [comment]
Great that you find a solution.
