### ISSUE TITLE
Can't Find Tiff2Pdf Class/Namespace

### ISSUE THREAD

**Issue by harlankoehn** [BitMiracle/libtiff.net#44]
There's code in the samples indicating that Tiff2Pdf is included as a library along with the other libraries. But I never could find it in the Object Browser of any of the .NET DLL's.

Here's the code in the documentation:
```
using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;

using BitMiracle.LibTiff.Classic;

namespace BitMiracle.LibTiff.Samples
{
    public static class ConvertTiffToPdf
    {
        public static void Main()
        {
            string inputFile = @"Sample Data\multipage.tif";
            string outputFile = "output.pdf";

            string[] arguments = new string[] { "-o", outputFile, "-p", "A4", inputFile };
            BitMiracle.Tiff2Pdf.Program.Main(arguments);

            Process.Start(outputFile);
        }
    }
}

```

**Comment by Bobrovsky** [comment]
You should add Tiff2Pdf**.exe** as a reference to you project. 

![tiff2pdf-reference](https://cloud.githubusercontent.com/assets/8809114/26338920/ec126550-3fa5-11e7-9b08-971cbb461daa.png)
