### ISSUE TITLE
WhitePoint and PrimaryChromaticities are not copied properly with TiffCP.

### ISSUE THREAD

**Issue by t246246** [BitMiracle/libtiff.net#46]
I compiled recent libtiff.net40 project (2.4.583.0) and tiffcp with Visual Studio 2017 using **.net 4.7** framework and execute tiffcp.

C:\libtiff\libtiff.net\TiffCP\bin\Release>TiffCP.exe C:/tmp/logo1.tif C:/tmp/logo2.tif
C:/tmp/logo2.tif: Warning, "WhitePoint": Information lost writing value (-1.343036E+09) as (unsigned) RATIONAL
C:/tmp/logo2.tif: Warning, "WhitePoint": Information lost writing value (-1.413044E+09) as (unsigned) RATIONAL
C:/tmp/logo2.tif: Warning, "PrimaryChromaticities": Information lost writing value (-1.417339E+09) as (unsigned) RATIONAL
C:/tmp/logo2.tif: Warning, "PrimaryChromaticities": Information lost writing value (-1.28849E+09) as (unsigned) RATIONAL
C:/tmp/logo2.tif: Warning, "PrimaryChromaticities": Information lost writing value (-6.442451E+08) as (unsigned) RATIONAL
C:/tmp/logo2.tif: Warning, "PrimaryChromaticities": Information lost writing value (-2.57698E+08) as (unsigned) RATIONAL

I checked it with tiffinfo/tiffdump come with libtiff 4.0.7 on cygwin.

$ tiffinfo logo1.tif
TIFF Directory at offset 0x6e04 (28164)
  Image Width: 640 Image Length: 480
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: palette color (RGB from colormap)
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 480
  Planar Configuration: single image plane
  Page Number: 0-1
  Color Map: (present)
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000

$ tiffinfo logo2.tif
TIFF Directory at offset 0x6e0c (28172)
  Image Width: 640 Image Length: 480
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: palette color (RGB from colormap)
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 480
  Planar Configuration: single image plane
  Page Number: 0-1
  Color Map: (present)
  White Point: 0-0
  PrimaryChromaticities: 1546188288.000000,0.000000,0.000000,1717986816.000000,0.000000,0.000000

And tried to copy the same input file with original tiffcp come with libtiff 4.0.7

$ tiffcp logo1.tif logo3.tif

$ tiffinfo logo3.tif
TIFF Directory at offset 0x6e04 (28164)
  Image Width: 640 Image Length: 480
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: palette color (RGB from colormap)
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 480
  Planar Configuration: single image plane
  Page Number: 0-1
  Color Map: (present)
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000

So something is wrong with libtiff.NET version for RATIONAL tag.

PS: logo1.tif is created by ImageMagick 7.0.7-1 Q16 by using the followng command:
magick logo: logo1.tif

**Comment by t246246** [comment]
After quick look, in fetchRationalArray() in Tiff_DirRead.cs, **byte[] l** is correctly read after fetchData(), however, result float value is wrongly become negative. As these tags are RATIONAL not SRATIONAL.

Chaging **int[] pair** to **uint** and cast the return value from readInt(), i.e.

`
 uint[] pair = new uint[2];
                for (int i = 0; i < dir.tdir_count; i++)
                {
                    pair[0] = (uint)readInt(l, offset);
                    offset += sizeof(int);
                    pair[1] = (uint)readInt(l, offset);
`
these tags are correctly written.  But for real fix, we have to distinguish RATIONAL and SRATIONAL somehow.

**Comment by Bobrovsky** [comment]
Thank you for the findings and for the PR. Even though I closed your PR without merging it, thank you for the PR, it was a great start for implementing a fix.
