### ISSUE TITLE
How to split a tiff image into smaller chunks

### ISSUE THREAD

**Issue by syedhassaanahmed** [BitMiracle/libtiff.net#50]
Hi,

I'm new to tiff image processing and would like to split a single-page tiff raster (20000 * 20000) into 100 smaller tiff files (each of size 200 * 200) using `libtiff.net`. Similar to as described in [this article](https://howtoinqgis.wordpress.com/2016/12/17/how-to-split-a-raster-in-several-tiles-using-qgis-or-python-gdal/) using Python (GDAL).

I've looked at [the samples](https://bitmiracle.github.io/libtiff.net/?topic=html/e4f25423-eede-4ef6-a920-9cb539d056c6.htm) but couldn't find it.

**Comment by andirinli** [comment]
Here is some of my code.
I hope it help you

`-
			.......

			int TileImagePixelSize = 256;
			var width = tif.GetField(TiffTag.IMAGEWIDTH).First().ToInt();
            var height = tif.GetField(TiffTag.IMAGELENGTH).First().ToInt();
			
			
			int HorizontalTileCount = (int)Math.Ceiling((double)width / TileImagePixelSize);
			int VerticalTileCount = (int)Math.Ceiling((double)height / TileImagePixelSize);
			
            byte[] imgData;
			System.Windows.Media.Imaging.CroppedBitmap cb;
			
			
            var totalTileCount = HorizontalTileCount * VerticalTileCount;

            int counter = 0;
            int percent = 0;

            int tifStride = tif.ScanlineSize();

            ///tilerow :
			///Height = TileImagePixelSize(256)
            ///Width = Tif Image Width
            int tileRowDataSize = tifStride * TileImagePixelSize;

            int totalReadSize = 0;

            ///byte count for each tilerow
            int readSizeForTileRow = 0;

            for (int row = 0; row < VerticalTileCount; row++)
            {
                int tileRowOffset = 0;

                /// byte[] for each tilerow
                var tileRowData = new byte[tileRowDataSize];

                ///calculate readSize for this tilerow 
                if ((totalReadSize + TileImagePixelSize) < PixelHeight)
                    readSizeForTileRow = TileImagePixelSize;
                else
                    readSizeForTileRow = PixelHeight - totalReadSize;

                ///for tilerow in tif file readTifRowNumber calculation
                int offset = row * TileImagePixelSize;


                #region TileRow Data Read
                for (int l = 0; l < readSizeForTileRow; l++)
                {
					
                    var readTifRowNumber = l + offset;
                    var tifRowData = new byte[tifStride];
                    tif.ReadScanline(tifRowData, readTifRowNumber);

                    Buffer.BlockCopy(tifRowData, 0, tileRowData, tileRowOffset, tifStride);

                    tileRowOffset += tifStride;
                }
                #endregion

                totalReadSize += readSizeForTileRow;

                ///create bitmapsource for each tilerow
                var tempBitmap = BitmapSource.Create(PixelWidth, readSizeForTileRow, XDPI, YDPI, PixelFormats.Rgb24, null, tileRowData, tifStride);
                ///convert to bgra32 format --- normaly not necessary
				bs = new FormatConvertedBitmap(tempBitmap, PixelFormats.Bgra32, null, 0);

                #region Tilerow to tile split

                for (int x = 0; x < HorizontalTileCount; x++)
                {
                    var xOffset = x * TileImagePixelSize;
                    int widthSize = TileImagePixelSize;
					
                    ///Check last piece. otherwise exception
                    if ((xOffset + TileImagePixelSize) > PixelWidth)
                        widthSize = PixelWidth - (x * TileImagePixelSize);

					///this is the tile
                    cb = new CroppedBitmap(bs, new Int32Rect(xOffset, 0, widthSize, readSizeForTileRow));
					
					
					var fName = string.Format(@"{2}\{0}x{1}.png", x, row, Settings.TempDirectory);
                    saveAsFile(cb, fName);
                }
            }

`

**Comment by syedhassaanahmed** [comment]
Hi @andirinli Thanks for the code, really appreciate your help. However it doesn't compile for me due to missing variables and methods and since I'm new to image processing and libtiff.net, its hard to get a context. Would it be possible for you to provide the full source of this class in a GitHub repo? Thanks

**Comment by andirinli** [comment]
https://gist.github.com/andirinli/ae94455a5c4f05766fc36e37afc35b3e

**Comment by syedhassaanahmed** [comment]
@andirinli It crashes with `System.ArgumentException: Value does not fall within the expected range` when trying to create `CroppedBitmap`. What values did you use for `PixelWidth` and `PixelHeight`?

**Comment by andirinli** [comment]
PixelWidth  = width;
PixelHeight = height;
sory about that.
i'm writing on linux system thats why i can't test right now.

**Comment by syedhassaanahmed** [comment]
Here is my code to do the same with strips https://github.com/syedhassaanahmed/usql-split-tiff/blob/master/SplitTiff/SplitTiff.cs Would love if someone can review it.
