### ISSUE TITLE
Info needed: How to set existing metadata  of Existing multipage tif file.

### ISSUE THREAD

**Issue by Raveendra-Pai** [BitMiracle/libtiff.net#52]
I am trying to set existing metadata tag to the existing Tiff image with 2 pages. eg: Author(ARTIST) tag (ItemID 315) using libTiff.Net. 
using this link : [http://bitmiracle.github.io/libtiff.net/html/f47d1201-0893-45dc-907e-2bbeb5e3cb0c.htm](url), I have changed tag id to 315 instead of 42112 and tried running code, The "Author" metadata is setting properly. But the output tiff first page has proper image and second page has black patch.
Please let me know is there any way to set the metadata especially for multipage Tiff file using libTiff.Net library. 
Thanks in advance

**Comment by Bobrovsky** [comment]
You might get better luck with questions like this on StackOverflow.com
