### ISSUE TITLE
Invalid warning about unsorted tags when consecutive unknown tags encountered

### ISSUE THREAD

**Issue by cmbirnbaum** [BitMiracle/libtiff.net#53]
I was checking the compatibility of some files with this library and I found a bug.  The attached file has the tags XPTitle and XPComment (40091 and 40092), which are shown by Windows' file properties dialog.  This library will overshoot when iterating over known tags for each unknown tag, leading to the erroneous out of order check.

The simple fix is to add "fix--;" after the first "haveunknowntags = true;" in Tiff.cs.  A better fix would be to replace the ill advised iterating over the known tag list with a simple hashtable.

By the way I also encountered bugs involving bigtiff support that appear to have been fixed on github but not in the official release.  Do you plan to update the official release with these fixes?  Thanks.

[ordered_tags.tif.zip](https://github.com/BitMiracle/libtiff.net/files/1911545/ordered_tags.tif.zip)

**Comment by Bobrovsky** [comment]
Hello, 

Thank you for your bug report and for the test file. 

Unfortunately, the simple fix proposed by you is not correct. It will cause no warnings even if tag 40092 will come before 40091 in the directory.

The official release is indeed behind of the code in the repo. We'll try to fix this.
