### ISSUE TITLE
Not able to open LibTiff and UnitTests csproject in VS 2015

### ISSUE THREAD

**Issue by WindingWinter** [BitMiracle/libtiff.net#55]
The error when opening the csproject file is

> error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by Bobrovsky** [comment]
The projects should be opened in Visual Studio 2017.
