### ISSUE TITLE
Not returned from NumberOfDirectories() for intentionally broken tiff.

### ISSUE THREAD

**Issue by t246246** [BitMiracle/libtiff.net#58]
Attached tiff is intentionally looped, i.e. next IFD of 2nd page is pointed to 1st page.
When I read this tiff and call NumberOfDirectories()
```
Stream stream = File.Open("../../logo2.tif", FileMode.Open, FileAccess.Read);
using (var inFile = Tiff.ClientOpen(string.Empty, "r", stream, new TiffStream()))
{ 
    Console.Out.WriteLine(inFile.NumberOfDirectories());
}
```
program never returns.

IMHO, most tiff handling program first checks the number of page, so I think this should throw some exception to avoid DOS attack.

[logo2.zip](https://github.com/BitMiracle/libtiff.net/files/3379842/logo2.zip)

**Comment by Bobrovsky** [comment]
Thank you for the report and for the file. Your suggestion makes sense. Are you going to submit a PR with a fix?

**Comment by t246246** [comment]
Just send a PR https://github.com/BitMiracle/libtiff.net/pull/59

**Comment by Bobrovsky** [comment]
Thank you. I merged the PR.
