### ISSUE TITLE
TiffCp doesn't fail on certain errors

### ISSUE THREAD

**Issue by makingbloke** [BitMiracle/libtiff.net#61]
In TiffCp if certain errors occur (I'm copying a page which has a non standard JPEG compression - but it's not OJPEG :) ) then the directory is copied but the page data is not. This means you end up with a Tiff file where one page is not readable. If one page cannot be read would it better for TiffCP to fail?

I debugged this using my image. In Tiff.cs at line 5304 (in the function WriteEncodedStrip) the function EncodeStrip is failing so the function is returning 0. This means the directory gets written but not an image data. Would it be better to return -1 and abandon the copy? (or only return 0 if we are ignoring errors? - I can see several cases in Tiff.cs where an error is displayed but a function returns 0.)

**Comment by Bobrovsky** [comment]
According to the documentation, WriteEncodedStrip returns
> The number of encoded and written bytes or <c>-1</c> if an error occurred.

So, if the function returns 0, you can be sure it didn't write any data. In my opinion, this covers the use case you described.

**Comment by makingbloke** [comment]
Not really because we end up with a tiff containing a corrupt page. Using
another example, I’m calling the copier.cs class from my code to copy a
page. How do you determine the page is corrupt if the copier function is
returning true even though it’s written an invalid Tiff?

Cheers

**Comment by Bobrovsky** [comment]
In your first message you were talking about Tiff class from the library. Now you are talking about Copier class from TiffCp utility. 

If you think there is an issue in code, then please try to be more specific about where it resides. And please feel free to send us pull requests with fixes.

**Comment by makingbloke** [comment]
Apologies, hopefully this clarification will make more sense. 

I can reproduce this issue using tiffcp.exe. I have a sample TIFF with 11 pages (unfortunately I cannot share it as it contains client data). Page 3 is JPEG encoded and the other pages use Group4. When TiffCp tries to copy page 3 it reports an error "JPEGLib: Not implemented yet". This then writes out a page with an incomplete directory entry and no image data. My point is, if the code reaches an error like this then I think it should abort the copy rather than write a malformed directory entry to the output tiff. 

I debugged the issue and traced through the source code and found it was happening because when the error occurred in WriteEncodedStrip in Tiff.cs (line 5303) instead of returning -1 which would indicate an error it's returning 0 so the calling function thinks nothing has been read and carries on.

As I said I cannot attach the original Tiff but I've attached a zip file containing a dump of the tags from the source Tiff (sample.txt -  it's a quite old one created by Imaging for Windows) and also the corrupt Tiff created by TiffCp (sample.tif). As you can see it's creating a header with no StripOffsets or RowsPerStrip. 

I hope this makes more sense, thanks for your time and your patience.

Cheers
[sample.zip](https://github.com/BitMiracle/libtiff.net/files/3499025/sample.zip)
