### ISSUE TITLE
How to use libtiff.net to split tif into single image?

### ISSUE THREAD

**Issue by futureflsl** [BitMiracle/libtiff.net#64]
I Want to use this library to get all frames,like this
public List\<Bitmap\> GetAllTiffFrames(string tifPath)
{

}
if tif file have three frames,the function will return three bitmaps to list,but I do not know how to fill code to the function.

**Comment by Bobrovsky** [comment]
Closing because it is not an issue.

**Comment by futureflsl** [comment]
is it not an issue?

**Comment by futureflsl** [comment]
ok,see you never
