### ISSUE TITLE
Missing implementation of CFARepeatPatternDim, possibly CFAPattern and CFA Photometric interpretation

### ISSUE THREAD

**Issue by TomArrow** [BitMiracle/libtiff.net#65]
Trying to write a DNG using this library like in this example that was done in C++: https://lab.apertus.org/T759

I dunno how to do the CFARepeatPatternDim tag, as it doesn't seem to be implemented. Also, CFAPattern doesn't seem to exist, however EXIF_CFAPATTERN exists, is that the same thing? 

And the photometric interpretation as CFA pattern and linear data doesn't seem to exist. I think I can just enter the correct number instead, but I'm not sure.

See page 20 of the DNG spec: https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf

**Comment by Bobrovsky** [comment]
Hello Tom,

The features you mentioned were probably added in a version of libtiff newer than the version we based our library on. 

Please feel free to create a PR with code that implements all the missing features.
