### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by katzsmile** [BitMiracle/libtiff.net#66]
I have a very large TIFF of size 19592*40325 pixels.
And when I create a new array for it, I immediately get System.OutOfMemoryException.

int imageSize = width * height;
int[] raster = new int[imageSize];
input.ReadRGBAImageOriented(width, height, raster, BitMiracle.LibTiff.Classic.Orientation.TOPLEFT);

So, is there any other way to get the raster as a Bitmap without converting it to RGBA first?

**Comment by makingbloke** [comment]
I assume when you are writing your image you are writing it in strips
rather than just one large strip? If so use ReadRGBAStrip to read it back
in chunks.

Cheers
