### ISSUE TITLE
Failed to read specific tag at SetDirectory()

### ISSUE THREAD

**Issue by t246246** [BitMiracle/libtiff.net#67]
Attached test.tiff is taken from ImageMagick forum https://imagemagick.org/discourse-server/viewtopic.php?p=171840&sid=d9679f9cf51a671c5ad80b78138cee9e#p171840

I tested it on current LibTiff.NET and got the error:
```
        static void Main(string[] args)
        {
            using (Stream stream = new FileStream(args[0], FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                using (var inImage = Tiff.ClientOpen(string.Empty, "r", stream, new TiffStream()))
                {
                    short totalPages = inImage.NumberOfDirectories();
                    for (short i = 0; i < totalPages; i++)
                    {
                        bool ret = inImage.SetDirectory(i);
                        Console.Out.WriteLine(string.Format("{0}: {1}", i, ret));
                    }
                }
            }
        }
```

Result: 
0: True
1: True
2: True
3: True
4: True
5: True
6: True
7: True
8: True
: Cannot handle different per-sample values for field "SMinSampleValue"
9: False

So I checked the code and tiff spec and found this error is checked  at fetchPerSampleAnys() in Tiff_DirRead.cs.
According to libtiff mailing list, it is the limitation of libtiff:
https://www.asmail.be/msg0055373960.html
All the values have to be the same.

SMinSampleValue (340) FLOAT (11) 3<0.00610352 0.00720215 0.00146484>
SMaxSampleValue (341) FLOAT (11) 3<15.125 15.125 15.3125>

However it does not affect the image presentation.
https://www.awaresystems.be/imaging/tiff/tifftags/minsamplevalue.html
(Strictly, the description is for obsolete(?) MinSampleValue and not for SMinSampleValue, but I guess the meaning is the same.)

So I'd like to remove this tag first as a workaround.

Using libtiff command, it is easy:

% tiffset -d 9 -u 340 test.tiff
% tiffset -d 9 -u 341 test.tiff

Then the modified file becomes able to be handled with LibTiff.NET.
However, Id' like to accomplish this with LibTiff.NET if possible.

Even using TiffCP.exe compiled from your TiffCP project,

% libtiff.net-master/TiffCP/bin/Debug/TiffCP.exe test.tiff a.tif
test.tiff: Cannot handle different per-sample values for field "SMinSampleValue"
test.tiff,9 not found!

because it uses ReadDirectory() as well.

Note that original tiffcp comes with libtiff can copy this file.

So, here is the question.

Is it necessary to check this value at ReadDirectory() ?
If so, how to remove problematic SMinSampleValue tag using LibTiff.NET?

Best Wishes,
[test.zip](https://github.com/BitMiracle/libtiff.net/files/4070970/test.zip)

PS.  This file can be opened with Gimp, Krita and Mac preview, but Windows Photo Viewer failed to read it.

**Comment by Bobrovsky** [comment]
Hello,

You can implement something like TIFFUnsetField function in libtiff. With TIFFUnsetField you can implement a portion of tiffset utility to accomplish your goal. Please feel free to send us a PR with you improvements.

The check is necessary for the reasons described in https://www.asmail.be/msg0055373960.html
