### ISSUE TITLE
Out of Memory Exception when Exporting All Directories

### ISSUE THREAD

**Issue by pterrito** [BitMiracle/libtiff.net#68]
Recently I was exploring the TiffTo32BitBitmap example on the site, and this worked well for a single directory. Interestingly, if one loops over all of the directories and exports the images sequentially, I am getting an out of memory exception when trying to allocate the raster array. This works for the first 6 directories, but runs out of memory on the 7th.

Below is the code I am using, which is a slight derivative of the example, and only loops over the directories to export the bitmaps. 

Imports System.Drawing
Imports System.Drawing.Imaging
Imports BitMiracle.LibTiff.Classic

Module Module2

    Public NotInheritable Class TiffTo32BitBitmaps

        Public Sub New(FileName As String)

            Using tif As Tiff = Tiff.Open(FileName, "r")

                Dim directorycount As Integer = tif.NumberOfDirectories

                For i As Integer = 0 To directorycount - 1
                    tif.SetDirectory(i)

                    ' Find the width and height of the image
                    Dim value As FieldValue() = tif.GetField(TiffTag.IMAGEWIDTH)
                    Dim width As Integer = value(0).ToInt()

                    value = tif.GetField(TiffTag.IMAGELENGTH)
                    Dim height As Integer = value(0).ToInt()

                    ' Read the image into the memory buffer
                    Dim raster As Integer() = New Integer(height * width - 1) {}
                    If Not tif.ReadRGBAImage(width, height, raster) Then
                        System.Windows.Forms.MessageBox.Show("Could not read image")
                        Return
                    End If

                    Using bmp As New Bitmap(width, height, PixelFormat.Format32bppRgb)
                        Dim rect As New Rectangle(0, 0, bmp.Width, bmp.Height)

                        Dim bmpdata As BitmapData = bmp.LockBits(rect, ImageLockMode.ReadWrite, PixelFormat.Format32bppRgb)
                        Dim bits As Byte() = New Byte(bmpdata.Stride * bmpdata.Height - 1) {}

                        For y As Integer = 0 To bmp.Height - 1
                            Dim rasterOffset As Integer = y * bmp.Width
                            Dim bitsOffset As Integer = (bmp.Height - y - 1) * bmpdata.Stride

                            For x As Integer = 0 To bmp.Width - 1
                                Dim rgba As Integer = raster(rasterOffset)
                                rasterOffset = rasterOffset + 1
                                bits(bitsOffset) = CByte((rgba >> 16) And &HFF)
                                bits(bitsOffset + 1) = CByte((rgba >> 8) And &HFF)
                                bits(bitsOffset + 2) = CByte(rgba And &HFF)
                                bits(bitsOffset + 3) = CByte((rgba >> 24) And &HFF)
                                bitsOffset = bitsOffset + 4
                            Next
                        Next

                        System.Runtime.InteropServices.Marshal.Copy(bits, 0, bmpdata.Scan0, bits.Length)
                        bmp.UnlockBits(bmpdata)

                        Dim tFile As String = System.IO.Path.GetFileNameWithoutExtension(FileName)
                        Dim tDir As String = System.IO.Path.GetDirectoryName(FileName)
                        Dim tOutFileName As String = System.IO.Path.Combine(tDir, tFile & "_" & i & ".tif")
                        bmp.Save(tOutFileName)
                        'System.Diagnostics.Process.Start(tOutFileName)
                        Console.WriteLine("Exporting: " & tOutFileName)
                    End Using
                    tif.FreeDirectory()
                Next
            End Using
        End Sub
    End Class

End Module

**Comment by Bobrovsky** [comment]
There are can be different causes to the issue. Two most common causes are:
1. Large Object Heap fragmentation. 
2. The size of the image is too large and the raster array requires more memory than available in the device. This is especially true for 32bit processes.

In any case, the issue is not directly related to the library and can not be fixed _inside_ or _by_ the library.

**Comment by pterrito** [comment]
Hello Sergey,

Thanks for the quick reply.

This make perfect sense, as these images somewhat large (593 MB). I would have expected that in .Net if I do a cleanup of objects, and in the extreme case for memory collection via GC.Collect, that we should be able to export these images sequentially. I have tried this in parallel as well, and get the same issue, but since these are all requesting memory blocks at the same time, that this would be challenging.

So with this in mind, could you recommend a solution which would resolve these limitation? So for instance, we could build these as 8bpp indexed, but I could not find an example which describes this on the website. Could you provide an example which does this??

Any help in the right direction would be most appreciated!!

Best,

Paul R. Territo, Ph.D
Associate Professor of Research
Associate Professor of Electrical and Computer Engineering
Associate Professor of Stark Neurosciences Research Institute
Department of Radiology and Imaging Sciences
Indiana University, School of Medicine
950 West Walnut Street
R2-E124
Indianapolis, IN 46202-5181
(P) 317-278-3313
(F) 317-274-1067
(E) pterrito@iupui.edu<mailto:pterrito@iupui.edu>
