### ISSUE TITLE
CMYKA support

### ISSUE THREAD

**Issue by arthurshayne** [BitMiracle/libtiff.net#7]
This project is wonderful.
I have a 40bit depth TIF file which is using CMYKA.
The .Net Image.FromFile method will be throw out of memory exception when load it in. I think the .Net Image class don't support CMYKA image.
I tried this project, it can load it and convert it into PNG file. But the transparent background will turn to white.
I debug the project, I found the TiffRgbaImage.putRGBcontig8bitCMYKtitle method only treated the CMYK to RGB situation. Does this project plan to support CMYKA TIF?
By the way, when image is CMYKA the samplesperpixel is 5.

**Comment by Bobrovsky** [comment]
We do not plan to add CMYKA support ourselves. Please feel free to implement the support and send us a pull request.

**Comment by arthurshayne** [comment]
Hi, I have created a pull request. If anything wrong or need improve please let me know. Thank you!

**Comment by Bobrovsky** [comment]
Hi, Thank you for the pull request. Do you have any (relatively small) TIFF files to test your additions?

**Comment by arthurshayne** [comment]
Hi, I have added test image to the pull request, also changed test class. Please take a look at them. Thank you!

**Comment by Bobrovsky** [comment]
Thank you! Unfortunately, the test images are very big (19 MB total and about 4 MB for expected results). Could you please use smaller images? 

You can also compress the test images (now they are uncompressed but can be compressed really well using tiffcp utility and LZW compression). You might also want  to convert only part of the image to RGBA. Please note that Tiff.ReadRGBAImage should be able to convert only portion of the image.

**Comment by arthurshayne** [comment]
Hi, I resized image gray8a-tile.tif and compress it by LZW (Use PhotoShop Element 12). I compressed cmyka-tile.tif by tiffcp(awesome utility by the way).
Now 858K total and 393K for expected results. Is this OK?
Thank you for your tips. In my project, I just need to convert the whole image. If I want to convert only portion of the image, I just use a smaller width and/or height is OK, right?

**Comment by Bobrovsky** [comment]
Hi,

Thank you for your help. I merged (partially) you pull request. 

> If I want to convert only portion of the image, I just use a smaller width and/or height is OK, right?

Yes.
