### ISSUE TITLE
Non-file-based streams?

### ISSUE THREAD

**Issue by lesscodetxm** [BitMiracle/libtiff.net#70]
Is there a way to open `Tiff` instances that are backed by streamed content that are not files?
I was looking for a Tiff to Pdf converter that could be used in an Asp.Net web service to stream in Tiff files from another service, convert the content, and stream out Pdf content in a response, without having to touch the file system.

I was able to hack a couple of new methods into `Tiff` and `ExtenderAndErrorHandler` to allow me to basically hand my own input stream into `ClientOpen`, and then use the `T2P` class as-is to convert the Tiff in-memory and stream out the result.

But maybe I'm missing something obvious and this use case is already supported?

**Comment by Bobrovsky** [comment]
Hello,

You can open streams with TIFF using the following code:

`Tiff image = Tiff.ClientOpen("in-memory", "r", memStream, new TiffStream());`

In the code above, memStream is a System.IO.Stream. Not necessarily a memory stream.

**Comment by lesscodetxm** [comment]
Thanks, Sergey. That's basically what I'm doing - just wanted to make sure that was the right way.
