### ISSUE TITLE
Error When trying to get Tile (Width-Height)

### ISSUE THREAD

**Issue by sisocano** [BitMiracle/libtiff.net#72]
Hi There 
im using Unity 2019.2 and BitMiracle v2.4.6, i want to read 32-64 floating point Tiff files
so im using this code :

           ` using (Tiff image = Tiff.Open(filePath, "r"))
            {
                const int pixelStride = 4; // bytes per pixel

                int imageWidth = image.GetField(TiffTag.IMAGEWIDTH)[0].ToInt();
                int imageHeight = image.GetField(TiffTag.IMAGELENGTH)[0].ToInt();
                int tileCount = image.NumberOfTiles();
                int tileSize = image.TileSize();
                Debug.Log(tileSize);
                //Im Getting Error Here 
                **### int tileWidth = image.GetField(TiffTag.TILEWIDTH)[0].ToInt();
                int tileHeight = image.GetField(TiffTag.TILELENGTH)[0].ToInt();**
                int tileStride = (imageWidth + tileWidth - 1) / tileWidth;

                floatheightData = new float[imageWidth, imageHeight];

                row_y = tileHeight;
                col_x = tileWidth;

                int bufferSize = tileWidth * tileHeight * pixelStride;
                byte[] buffer = new byte[bufferSize];

                fixed (byte* bufferPtr = buffer)
                {
                    float* array = (float*)bufferPtr;

                    for (int t = 0; t < tileCount; t++)
                    {
                        image.ReadEncodedTile(t, buffer, 0, buffer.Length);

                        int x = tileWidth * (t % tileStride);
                        int y = tileHeight * (t / tileStride);

                        var copyWidth = Math.Min(tileWidth, imageWidth - x);
                        var copyHeight = Math.Min(tileHeight, imageHeight - y);

                        for (int j = 0; j < copyHeight; j++)
                        {
                            for (int i = 0; i < copyWidth; i++)
                            {
                                var el = array[j * tileWidth + i];
                                data.floatheightData[x + i, y + j] = el;

                            }
                        }
                    }
                }
}
`
Unity Error When try to access to tileWidth  :
NullReferenceException: Object reference not set to an instance of an object

any Help please to load That Type of Tiff and to solve this issue

**Comment by Bobrovsky** [comment]
Hi,

Please ask questions like this on StackOverflow.
