### ISSUE TITLE
Binaries for newest version?

### ISSUE THREAD

**Issue by PyroGenesis** [BitMiracle/libtiff.net#73]
Hi,

Where can I find the binaries for the latest version of `libtiff.net`? There used to be a link to the binaries on the website before, but it seems to be removed now.

I am specifically looking for `Tiff2Pdf.exe`.

P.S.: I tried to build the repo myself but that gave me an error in the `.csproj` file
![image](https://user-images.githubusercontent.com/17806916/87734871-aff88180-c788-11ea-8c7f-5235bd2f61d2.png)

**Comment by shibaev** [comment]
We only maintain binaries on NuGet now, which includes the compiled version of BitMiracle.LibTiff.Net.dll. The last version of binaries that includes Tiff2Pdf.exe is 2.4.560.0. You can download it here: https://bitmiracle.com/builds/libtiff.net_bin-2.4.560.0.zip

To build the source code make sure that you use Visual Studio 2017 or 2019 with .NET Core support. Read this answer for more detail: https://stackoverflow.com/a/42509354/136138
