### ISSUE TITLE
linkDirectory() causes quadratically slow multi page writing

### ISSUE THREAD

**Issue by xela-trawets** [BitMiracle/libtiff.net#74]
Writing multi page tiffs is quadratically slow
For thousands of frames this becomes a problem
This is due to walking the directories from the root in linkDirectory() in Tiff_DirWrite.cs

This can be mitigated by Stashing the value of nextdir at the top of the while loop (around line 1806 of Tiff_DirWrite.cs)
This is fragile and breaks if the directories are altered between calls to linkDirectory (for instance by reWriteDirectory
How ever it is simpler than making a dictionary or lookup for the pages, and does the job I need.

Would you be interested if I put some effort in to catch the places in the code which would invalidate the stashed value, to make this work in all cases, Or is this just too Hacky, (and departs from the old libTiff behavior)

Hope this makes sense...

**Comment by Bobrovsky** [comment]
Thanks for the message. Yes, the directory traversal is slow in the current implementation. 

We are definetely interested in making directory traversal faster in both reading and writing scenarios. It is ok to introduce something that is missing in the original libtiff. Of course, we would prefer an implementation that does not break by a valid library method call. 

We had a PR before (PR #71) about improvements to reading of directories. You might want to look at the PR. Unfortunately, that PR author didn't complete the work, so the PR is not merged.

**Comment by xela-trawets** [comment]
The changes needed to implement a general lookup for the directory offsets would be widespread I imagine, so this would no longer track the C library. 

Therefore a plan might be a small targeted change.
The effect is manifest at the application level in WriteDirectory.

The proposal might be limited to implementing "WriteDirectoryFaster", which would not affect behavior if not used.

**Comment by xela-trawets** [comment]
Hi Sergey,

I have a minimal patch that I am happy with
The patch stashes the directory offset from the top of the directory walk loop in LinkDirectory() and RewriteDirectory()
This lets us jump to the tail of the list
 
WriteDirectory() calls LinkDirectory(), so writing long sequences of directories is no longer slow
The stashed value is invalidated if the Header is rewritten; eg. switch to BigTiff
The stashed value is invalidated by UnlinkDirectory()
The stashed value is invalidated by WriteCustomDirectory()

I will try and make a PR, but I am a complete beginner at Git.

A

**Comment by xela-trawets** [comment]
ps We dont jump to the very tail, but the directory preceeding the tail,
Rewrite directory would otherwise be a problem

**Comment by Bobrovsky** [comment]
Great! The description looks very promising. 
Please try and prepare a PR with your changes. I will be happy to review it.

**Comment by xela-trawets** [comment]
Thanks, I needed the nudge, things get busy...
expect to get to this over the Weekend

**Comment by Bobrovsky** [comment]
I merged your PR and then switched the library to always using the optimized approach. Thank you for the help.

**Comment by stephtr** [comment]
Since I am also running into this issue, I was wondering whether it would be possible to release a new version to nuget?

**Comment by Bobrovsky** [comment]
@stephtr [Done!](https://www.nuget.org/packages/BitMiracle.LibTiff.NET/2.4.649)

**Comment by stephtr** [comment]
Thanks!
