### ISSUE TITLE
CMYK tiff image to RGB results with oversaturated colors

### ISSUE THREAD

**Issue by maxlego** [BitMiracle/libtiff.net#76]
I am using the [Converter](https://github.com/BitMiracle/libtiff.net/blob/6b7754b81fdfb49be9de01b5e48f2a96998ec6f0/Tiff2Rgba/Converter.cs) given in examples.

And the code is relatively simple

```
using (var tifImg = Tiff.ClientOpen("in-memory", "r", fs, new TiffStream()))
{
    using var rgbTiff = Tiff.Open(@"c:\temp\rgb.tiff", "w");
    new Converter().tiffcvt(tifImg, rgbTiff);
}

```

and the result is like this

![image](https://user-images.githubusercontent.com/189688/92438036-c29f9d80-f1b0-11ea-9113-0bbcc6c9173a.png)

where left is RGB and right is an original image

**Comment by Bobrovsky** [comment]
@maxlego This is a known limitation of the library. The CMYK->RGB conversion formula produces visually different results. 

As mentioned in TiffRgbaImage.cs:

> NB: The conversion of CMYKA->RGBA is *very* crude.

We would be happy to review a pull request with a fix for this issue.

**Comment by maxlego** [comment]
Any idea where to look better solution for conversion? All resources i have found, use same calculation.

**Comment by Bobrovsky** [comment]
No, unfortunately, no ideas.

**Comment by t246246** [comment]
To adjust color, use icc profile.  I'm not so familiar with this, but you need different way whether your input RGB file has icc profile or not.  Check other image related forum, for example imagemagick, and when you know what you should do, ask how to do it in LibTIff.NET.
