### ISSUE TITLE
SetField(TiffTag.IMAGEDESCRIPTION, xxx) cause crash when file size > 4GB

### ISSUE THREAD

**Issue by KaiWangCanada** [BitMiracle/libtiff.net#81]
![image](https://user-images.githubusercontent.com/10340634/122831056-4f869400-d2b7-11eb-8a58-4288fb823758.png)

when it crash, the file size just exceeded 4GB.

If commented out the SetField(TiffTag.IMAGEDESCRIPTION, xxx) line, then there was no crash. final file size is about 5GB.

Thanks!

**Comment by shibaev** [comment]
Could you please provide a sample app or a full code to reproduce the issue?

**Comment by KaiWangCanada** [comment]
> Could you please provide a sample app or a full code to reproduce the issue?

I'm terribly sorry for the mistake. Apparently the crash is caused by another bug, which is not libtiff.net related.

Sorry again!

**Comment by KaiWangCanada** [comment]
Apparently the crash is caused by another bug, which is not libtiff.net related.

Sorry!

**Comment by KaiWangCanada** [comment]
The crash seems come back. The code is modified from Sample CreateMultiTiff:
if ImageDescription was set to a const, then there is no crash. e.g.: `output.SetField(TiffTag.IMAGEDESCRIPTION, " " + page);`

`using System;
using System.Diagnostics;

using BitMiracle.LibTiff.Classic;

namespace BitMiracle.LibTiff.Samples
{
    public static class CreateMultipageTiff
    {
        public static void Main()
        {
            const int numberOfPages = 1700;

            const int width = 1392;
            const int height = 1040;
            const int samplesPerPixel = 1;
            const int bitsPerSample = 16;

            const string fileName = "CreateMultipageTiff.tif";

            using (Tiff output = Tiff.Open(fileName, "w"))
            {
                for (int page = 0; page < numberOfPages; ++page)
                {
                    output.SetField(TiffTag.IMAGEWIDTH, width);
                    output.SetField(TiffTag.IMAGELENGTH, height);
                    output.SetField(TiffTag.SAMPLESPERPIXEL, 1);
                    output.SetField(TiffTag.BITSPERSAMPLE, 16);
                    output.SetField(TiffTag.ORIENTATION, Orientation.TOPLEFT);
                    output.SetField(TiffTag.ROWSPERSTRIP, height);
                    output.SetField(TiffTag.XRESOLUTION, 88.0);
                    output.SetField(TiffTag.YRESOLUTION, 88.0);
                    output.SetField(TiffTag.RESOLUTIONUNIT, ResUnit.CENTIMETER);
                    output.SetField(TiffTag.PLANARCONFIG, PlanarConfig.CONTIG);
                    output.SetField(TiffTag.PHOTOMETRIC, Photometric.MINISBLACK);
                    output.SetField(TiffTag.COMPRESSION, Compression.NONE);
                    output.SetField(TiffTag.FILLORDER, FillOrder.MSB2LSB);

                    output.SetField(TiffTag.IMAGEDESCRIPTION, " " + page);

                    // specify that it's a page within the multipage file
                    output.SetField(TiffTag.SUBFILETYPE, FileType.PAGE);
                    // specify the page number
                    output.SetField(TiffTag.PAGENUMBER, page, numberOfPages);

                    Random random = new Random();
                    for (int i = 0; i < height; ++i)
                    {
                        short[] samples = new short[width];
                        for (int j = 0; j < width; j++)
                            samples[j] = (short)random.Next(0, short.MaxValue);

                        byte[] buffer = new byte[samples.Length * sizeof(short)];
                        Buffer.BlockCopy(samples, 0, buffer, 0, buffer.Length);
                        output.WriteScanline(buffer, i);
                    }

                    output.WriteDirectory();
                }
            }

            Process.Start(fileName);
        }
    }
}`

**Comment by hangy** [comment]
https://github.com/BitMiracle/libtiff.net/blob/178c3b876d5834fbc545ae8b0a7b692d980f4450/LibTiff/TiffStream.cs#L35

- `buffer.Length` is 5 with all items `0`
- `offset` is 0
- `count` is 20

https://github.com/BitMiracle/libtiff.net/blob/178c3b876d5834fbc545ae8b0a7b692d980f4450/LibTiff/Internal/Tiff_DirWrite.cs#L559-L561

The buffer is smaller than the size calculated afterwards. I was able to fix the original exception by creating the `buffer` with a size of `dir.tdir_count * sizeof(int)`, see #83. Using ImageJ, I was able to view the file, but for some reason, the page numbers looked off. Not sure if you have any better methods to verify the file is correct.

@KaiWangCanada Note that the size of the file causes a [`BigTIFF`](https://www.loc.gov/preservation/digital/formats/fdd/fdd000328.shtml) image to be created: https://github.com/BitMiracle/libtiff.net/blob/178c3b876d5834fbc545ae8b0a7b692d980f4450/LibTiff/Internal/Tiff_DirWrite.cs#L1769-L1775 Not all viewers are compatible with this TIFF extension, so you may need to check your use-case and other involved applications.

**Comment by KaiWangCanada** [comment]
@hangy thanks for the quick reply! And many thanks for the excellent lib 👍
