### ISSUE TITLE
SetField(TiffTag.COLORMAP, r, g, b) uses short[] instead of ushort[]

### ISSUE THREAD

**Issue by rolandfischer93** [BitMiracle/libtiff.net#82]
As far as I know the COLORMAP should be treated as ushort[] and not as short[]. [https://www.awaresystems.be/imaging/tiff/tifftags/colormap.html](https://www.awaresystems.be/imaging/tiff/tifftags/colormap.html)

If I write out a colormap and try to read it in again I get a short[] although i use ToUShortArray() on the FieldValue.

Example:

```
ushort[] original = new ushort[256];
for (int i = 0; i < 256; i++)
{
    original[i] = (ushort)(i * 256);
}
MemoryStream buffer;

using (MemoryStream imageStream = new MemoryStream())
{
    using (Tiff tif = Tiff.ClientOpen("checkPalette", "w", imageStream, new TiffStream()))
    {
        tif.SetField(TiffTag.IMAGEWIDTH, 1);
        tif.SetField(TiffTag.IMAGELENGTH, 1);
        tif.SetField(TiffTag.SAMPLESPERPIXEL, 1);
        tif.SetField(TiffTag.ORIENTATION, Orientation.TOPLEFT);
        tif.SetField(TiffTag.PLANARCONFIG, PlanarConfig.CONTIG);
        tif.SetField(TiffTag.PHOTOMETRIC, Photometric.PALETTE);
        tif.SetField(TiffTag.ROWSPERSTRIP, tif.DefaultStripSize(0));
        tif.SetField(TiffTag.BITSPERSAMPLE, 8);
        tif.SetField(TiffTag.COLORMAP, original, original, original);

        tif.WriteScanline(new byte[] { 0x00 }, 0);
    }
    buffer = new MemoryStream(imageStream.ToArray());
}
buffer.Seek(0, SeekOrigin.Begin);

using (Tiff tif = Tiff.ClientOpen("checkPalette", "r", buffer, new TiffStream()))
{
    // Check Palette
    FieldValue[] colormap = tif.GetField(TiffTag.COLORMAP);
    ushort[] r = colormap[0].ToUShortArray();
    ushort[] g = colormap[1].ToUShortArray();
    ushort[] b = colormap[2].ToUShortArray();

    Console.WriteLine($"Read palette is: {r.GetType()}");
    Console.WriteLine($"Original palette is: {original.GetType()}");
}
```

produces:

Read palette is: System.Int16[]
Original palette is: System.UInt16[]

**Comment by Bobrovsky** [comment]
You are correct, the COLORMAP tag value should be treated as ushort[]. And calling the `ToUShortArray` is also correct. 

Even though `r.GetType()` returns `System.Int16[]`, your code should work just fine. For example, if you run the following code, you should get the expected results (only non-negative numbers):
```
foreach (var u in r)
    Console.Write($"{u} ");
```
Why it happens so is briefly described in a [SO answer](https://stackoverflow.com/a/24332463/249690):

> The CLR specification says that ushort[] and short[] are compatible, since converting short to ushort preserves the representation. This is a similar mechanism to array covariance.

If you look in the `ToUShortArray` method implementation, you could notice that the code checks the type of the value and tries to convert it. The strange fact is: the CLR produces `true` for `if (m_value is ushort[])` even though `m_value` is actually a `short[]`.
