### ISSUE TITLE
Adobe deflate

### ISSUE THREAD

**Issue by CaedesCZ** [BitMiracle/libtiff.net#87]
Hi,
I have problem with opening TIFF which is compresed with Adobe deflate. Image always show as empty space. Is there any special way how to open Adobe deflate?

**Comment by Bobrovsky** [comment]
There is no special way for this compression. 

Could you post the file and the code you use?

**Comment by CaedesCZ** [comment]
I just use Tiff.ReadRGBAImage(). But now I see the Tiff is tiled. Should I
read it tile by tile?

Here is TIFF, please don't share it
https://uschovna.plzen.eu/zasilka/B0F5F755-338E-4263-BB04-BBE85AD45881


pá 5. 11. 2021 v 11:34 odesílatel Sergey Bobrovsky ***@***.***>
napsal:

**Comment by Bobrovsky** [comment]
`ReadRGBAImage` reads both strip- and tile-based images.

**Comment by CaedesCZ** [comment]
Hmm,
ok, here is example tiff: https://uschovna.plzen.eu/zasilka/B0F5F755-338E-4263-BB04-BBE85AD45881
Please tell me if you can open it.

**Comment by Bobrovsky** [comment]
I can process it with both the library and Tiff2Rgba utility.

**Comment by CaedesCZ** [comment]
You can do it with ".ReadRGBAImage(width, height, raster)" ?
For me it is return int arrey with lenght 81183262, which is right for my
picture with 9166x8857, but only 16858 ints have some data inside :-/

pá 5. 11. 2021 v 16:18 odesílatel Sergey Bobrovsky ***@***.***>
napsal:

**Comment by CaedesCZ** [comment]
Here is how I try to read tile data. In any case it returns zero bytes.

        using (Tiff image = Tiff.Open(@"C:/test2.tif", "r"))
        {
            if (image == null)
            {
                Debug.Log("Could not open incoming image");
                return;
            }

            FieldValue[] value = image.GetField(TiffTag.IMAGEWIDTH);
            int width = value[0].ToInt();

            value = image.GetField(TiffTag.IMAGELENGTH);
            int height = value[0].ToInt();

            int tileNumber = image.NumberOfTiles() / 2;

            byte[] buffer = new byte[image.TileSize()];

            image.ReadEncodedTile(tileNumber, buffer, 0, image.TileSize());

            int truebytes = 0;
            foreach (byte x in buffer)
            { if (x != 0B00000000) truebytes++; }

            Debug.Log(width + "w " + height + "h");
            Debug.Log(image.IsTiled());
            Debug.Log("reading tile " + tileNumber + " from " +
image.NumberOfTiles());
            Debug.Log(truebytes + " bytes have data from " + buffer.Length);
        }

po 8. 11. 2021 v 8:58 odesílatel Matouš Bolek ***@***.***> napsal:

**Comment by Bobrovsky** [comment]
You mix different approaches in one question. This confuses. 

Given that your image is mostly black, it is not something unexpected to have only black pixels in a tile. At the same time, there are non-black tiles in your image. 

After modifying your code to the following one:
```
using (Tiff image = Tiff.Open(@"d:\Downloads\test.tif", "r"))
{
    if (image == null)
    {
        Console.WriteLine("Could not open incoming image");
        return;
    }

    FieldValue[] value = image.GetField(TiffTag.IMAGEWIDTH);
    int width = value[0].ToInt();

    value = image.GetField(TiffTag.IMAGELENGTH);
    int height = value[0].ToInt();

    byte[] buffer = new byte[image.TileSize()];

    for (int i = 0; i < image.NumberOfTiles(); i++)
    {
        image.ReadEncodedTile(i, buffer, 0, image.TileSize());

        int truebytes = 0;
        foreach (byte x in buffer)
        { if (x != 0B00000000) truebytes++; }

        if (truebytes == 0)
            continue;

        Console.WriteLine(width + "w " + height + "h");
        Console.WriteLine(image.IsTiled());
        Console.WriteLine("reading tile " + i + " from " + image.NumberOfTiles());
        Console.WriteLine(truebytes + " bytes have data from " + buffer.Length);
    }
}
```

I get an output like this:
```
8857w 9166h
True
reading tile 52 from 1260
95572 bytes have data from 262144
8857w 9166h
True
reading tile 53 from 1260
134069 bytes have data from 262144
8857w 9166h
True
reading tile 54 from 1260
104848 bytes have data from 262144
8857w 9166h
True
reading tile 55 from 1260
75847 bytes have data from 262144
8857w 9166h
True
reading tile 56 from 1260
45636 bytes have data from 262144

```

Therefore, I do not reproduce ANY issues with you file.

**Comment by CaedesCZ** [comment]
Thank you very much for your time, that was my fault. When tiles works I
dont need  Tiff.ReadRGBAImage() any more.
Sorry.


po 8. 11. 2021 v 16:49 odesílatel Sergey Bobrovsky ***@***.***>
napsal:
