### ISSUE TITLE
Group3opt.FILLBITS not filling to byte boundary with CCITT Group 4 fax encoding.

### ISSUE THREAD

**Issue by mnmhomes** [BitMiracle/libtiff.net#9]
According to https://bitmiracle.github.io/libtiff.net/html/e00d6851-cf09-287f-638b-fc62c498351a.htm, 
     
Options for CCITT Group 3/4 fax encoding.
Possible values for TiffTag.GROUP3OPTIONS / TiffTag.T4OPTIONS and TiffTag.GROUP4OPTIONS / TiffTag.T6OPTIONS tags.

However the code does not support this.  Can it be added?

Additional information here: http://stackoverflow.com/questions/30630764/libtiff-net-group3opt-fillbits-is-not-filling-to-byte-boundary

Thank you.
-Mike

**Comment by Bobrovsky** [comment]
Hello Mike,

What makes you think that Group3Opt.FILLBITS should be supported in CCITTFAX4? 

Please note that LibTiff.Net is mostly a .NET version of original libtiff. Does the original library support FILLBITS with CCITTFAX4?

If the original library supports this or if you have strong evidence that such configuration should be supported then LibTiff.Net can also support it. But please make sure that we will probably won't have time to implement this ourselves any time soon. We will be happy to receive a pull request, though.

**Comment by mnmhomes** [comment]
What makes you think that Group3Opt.FILLBITS should be supported in CCITTFAX4?
*Because of the documentation.* https://bitmiracle.github.io/libtiff.net/html/e00d6851-cf09-287f-638b-fc62c498351a.htm
> **Group3Opt Enumeration 
 Options for CCITT Group 3/4 fax encoding.
 Possible values for TiffTag.GROUP3OPTIONS / TiffTag.T4OPTIONS and TiffTag.GROUP4OPTIONS / TiffTag.T6OPTIONS tags.**

**Comment by Bobrovsky** [comment]
Unfortunately, the docs can be inaccurate. 

Did you have a chance to verify that the original library support FILLBITS with CCITTFAX4?

**Comment by mnmhomes** [comment]
No I can look into now.

**Comment by Bobrovsky** [comment]
MIke,

I am personally not sure FILLBITS should be supported for CCITTFAX4 and since the original library doesn't support it, we probably won't add such support to the library.
